### PR TITLE
declared variable '''' confidence '''' before use, to make it work in 'strict mode' environment.

### PR DESCRIPTION
**Pull request by spikying**

### CODE REVIEW

**Comment by runk** [comment]
Thanks for the contribution! Can you please use 2 spaces for indentation? Otherwise diff is very big and hard to understand what's actually changed :)

**Comment by spikying** [comment]
I'm quite new to Github's etiquette.  Hope that I've solved it!  Thanks.

**Comment by runk** [comment]
Looking good :+1:  Merging

**Comment by runk** [comment]
v0.1.0 published on npm

**Pull request merged**
